### ISSUE TITLE
(method compute-value  (mem-usage)) in generators/mem-usage.lisp gets compile error.

### ISSUE THREAD

**Issue by Yehouda** [Shinmera/cari3s#3]
**(method compute-value  (mem-usage))** in generators/mem-usage.lisp gets a comple time error, because of bad let form. 

It looks like it is missing a + around the binding of the value **free**.

**Comment by Shinmera** [comment]
Somehow I don't (and never did) get a compile error for that form. What the hell

**Comment by Yehouda** [comment]
I was testing it on LispWorks, presumably you were using a different implementation.

**Comment by Shinmera** [comment]
I was using SBCL, which is typically very strict about things like that, and indeed it seems to catch other forms that mistreat the argument list, but not that one. Mysterious.
